import type { SVG } from '~/src/utils'

export const typesTemplate = {
  filename: 'types/svg-sprite.d.ts',
  getContents({ options }: any) {
    const keys = Object.entries(options.sprites as Record<string, SVG[]>)
      .flatMap(([sprite, icons]) =>
        icons.map((icon) => {
          return sprite === options.defaultSprite
            ? `'${icon.name}'`
            : `'${sprite}/${icon.name}'`
        }),
      )
      .sort()
    return [
      '// Generated by nuxt-sprite-svg',
      'declare module \'#svg-sprite-types\' {',
      `  export type SpriteIconName =\n    ${keys.join(' |\n    ')};`,
      '}',
      '',
    ].join('\n')
  },
}
