export const spritesTemplate = {
  filename: 'sprite-svg.mjs',
  getContents({ options }: any) {
    return [
      '// Generated by nuxt-sprite-svg',
      `export const path = "${options.publicPath}";`,
      `export const spriteClass = "${options.elementClass}";`,
      `export const defaultSprite = "${options.defaultSprite}";\n`,
    ].join('\n')
  },
}
